[book]
authors = ["Masaki Komagata"]
language = "ja"
multilingual = false
src = "src"
title = "Rails Programmer Textbook"
description = "Railsプログラマーになるための教科書"

[build]
build-dir = "docs"

[output.html]
git-repository-url = "https://github.com/fjordllc/textbook"